foxtel-platform-general-communication-api:
  env:
    SPRING_PROFILES_ACTIVE: staging,demo,json-logging
    NEW_RELIC_APP_NAME: communication-api
    NEW_RELIC_LICENSE_KEY: c3a6b94918f96d44af11c628b52630d59f5ad20c
    NEW_RELIC_AGENT_ENABLED: true
    NEW_RELIC_DISTRIBUTED_TRACING_ENABLED: true
    spring.datasource.url: jdbc:oracle:thin:@10.5.60.225:1700/SIT1WS.SMS.FOXTEL.COM.AU
    spring.datasource.username: muleapi
    spring.datasource.password: chamel#231
    auth.username: testPN
    auth.password: testPN
  probePath: /actuator/health
  livenessProbe:
    initialDelaySeconds: 66
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  readinessProbe:
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  replicaCount: 1
  resources:
    limits:
      cpu: 2000m
      memory: 5120Mi
    requests:
      cpu: 500m
      memory: 5120Mi
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 50
    targetCPUUtilizationPercentage: 35