dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.118
- name: foxtel-platform-communication-whispir-api
  repository: https://artifactory.cluster.foxsports-gitops-prod.com.au/artifactory/helm
  version: 1.0.1
- name: foxtel-platform-general-account-management-api
  repository: https://artifactory.cluster.foxsports-gitops-prod.com.au/artifactory/helm
  version: 1.0.19
- name: foxtel-platform-general-authentication-service
  repository: https://artifactory.cluster.foxsports-gitops-prod.com.au/artifactory/helm
  version: 1.0.5
- name: foxtel-platform-general-device-management-api
  repository: https://artifactory.cluster.foxsports-gitops-prod.com.au/artifactory/helm
  version: 1.0.13
- name: foxtel-platform-general-fieldservice-api
  repository: https://artifactory.cluster.foxsports-gitops-prod.com.au/artifactory/helm
  version: 1.0.3
- name: foxtel-platform-general-payment-management-api
  repository: https://artifactory.cluster.foxsports-gitops-prod.com.au/artifactory/helm
  version: 1.0.8
- name: foxtel-platform-general-sales-management-api
  repository: https://artifactory.cluster.foxsports-gitops-prod.com.au/artifactory/helm
  version: 1.0.11
